package view;

import controller.Controller;
import java.util.ArrayList;
import javax.swing.JLabel;
import javax.swing.JTable;
import model.InvoiceHeader;

/**
 *
 * @author helkaradawe
 */
public class InvoiceFrame extends javax.swing.JFrame {

    Controller controller;
    private ArrayList<InvoiceHeader> invoices = new ArrayList<>();

    /**
     * Creates new form InvoiceFrame
     */
    public InvoiceFrame() {
        super("Sales Invoice Generator");
        initComponents();
        this.controller = new Controller(this);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        invoice_table_01 = new javax.swing.JTable();
        invoice_number = new javax.swing.JLabel();
        invoice_number_label = new javax.swing.JLabel();
        InvoiceTable = new javax.swing.JLabel();
        invoice_date = new javax.swing.JLabel();
        Customer_name = new javax.swing.JLabel();
        invoice_total = new javax.swing.JLabel();
        invoice_itemlabel = new javax.swing.JLabel();
        Create_New_Ivvoice = new javax.swing.JButton();
        Delete_Invoice = new javax.swing.JButton();
        delete_invoice_Item = new javax.swing.JButton();
        invoice_total_label = new javax.swing.JLabel();
        invoice_date_label = new javax.swing.JLabel();
        customer_name_label = new javax.swing.JLabel();
        Create_New_Item = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        Invoice_Line_Table = new javax.swing.JTable();
        MenuBar = new javax.swing.JMenuBar();
        Menu = new javax.swing.JMenu();
        load = new javax.swing.JMenuItem();
        save = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setName("Sales Invoice Generator"); // NOI18N

        invoice_table_01.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "No.", "Date", "Customer", "Total"
            }
        ));
        invoice_table_01.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                invoice_table_01MousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(invoice_table_01);

        invoice_number.setText("Invoice Number");

        InvoiceTable.setText("Invoice Table");

        invoice_date.setText("Invoice Date");

        Customer_name.setText("Customer Name");

        invoice_total.setText("Invoice Total");

        invoice_itemlabel.setText("Invoice Items");

        Create_New_Ivvoice.setText("Create New Invoice");
        Create_New_Ivvoice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Create_New_IvvoiceActionPerformed(evt);
            }
        });

        Delete_Invoice.setText("Delete Invoice");
        Delete_Invoice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Delete_InvoiceActionPerformed(evt);
            }
        });

        delete_invoice_Item.setText("Delete Item");
        delete_invoice_Item.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delete_invoice_ItemActionPerformed(evt);
            }
        });

        Create_New_Item.setText("Create New Item");
        Create_New_Item.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Create_New_ItemActionPerformed(evt);
            }
        });

        Invoice_Line_Table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "No", "Item Name", "Item Price", "Count", "Item Total"
            }
        ));
        Invoice_Line_Table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Invoice_Line_TableMousePressed(evt);
            }
        });
        jScrollPane2.setViewportView(Invoice_Line_Table);

        Menu.setText("File");

        load.setMnemonic('L');
        load.setText("Load");
        load.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loadActionPerformed(evt);
            }
        });
        Menu.add(load);

        save.setMnemonic('S');
        save.setText("Save");
        save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveActionPerformed(evt);
            }
        });
        Menu.add(save);

        MenuBar.add(Menu);

        setJMenuBar(MenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(InvoiceTable)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 337, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(invoice_itemlabel)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Customer_name)
                                    .addComponent(invoice_total)
                                    .addComponent(invoice_date, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(invoice_number))
                                .addGap(51, 51, 51)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(invoice_number_label, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(invoice_total_label, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(customer_name_label, javax.swing.GroupLayout.DEFAULT_SIZE, 254, Short.MAX_VALUE)
                                    .addComponent(invoice_date_label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(Create_New_Item)
                                .addGap(57, 57, 57)
                                .addComponent(delete_invoice_Item, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(65, 65, 65))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 385, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(Create_New_Ivvoice)
                        .addGap(40, 40, 40)
                        .addComponent(Delete_Invoice, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(invoice_number)
                            .addComponent(invoice_number_label))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(invoice_date)
                            .addComponent(invoice_date_label))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Customer_name)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(invoice_total)
                                .addGap(18, 18, 18)
                                .addComponent(invoice_itemlabel))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(customer_name_label)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(invoice_total_label)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(7, 7, 7))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(InvoiceTable)
                        .addGap(20, 20, 20)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 331, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Create_New_Item)
                    .addComponent(delete_invoice_Item)
                    .addComponent(Delete_Invoice)
                    .addComponent(Create_New_Ivvoice))
                .addGap(16, 16, 16))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void loadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loadActionPerformed
        controller.fillTables(null, null);
    }//GEN-LAST:event_loadActionPerformed

    private void saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveActionPerformed
        controller.save();
    }//GEN-LAST:event_saveActionPerformed

    private void Create_New_IvvoiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Create_New_IvvoiceActionPerformed
        controller.showCreateInvoice(evt);
    }//GEN-LAST:event_Create_New_IvvoiceActionPerformed

    private void Delete_InvoiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Delete_InvoiceActionPerformed
        controller.deleteInvoice(evt);
    }//GEN-LAST:event_Delete_InvoiceActionPerformed

    private void invoice_table_01MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_invoice_table_01MousePressed
        controller.clickInvoiceTable(evt);
     }//GEN-LAST:event_invoice_table_01MousePressed

    private void delete_invoice_ItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delete_invoice_ItemActionPerformed
        controller.deleteInvoiceLine(evt);
    }//GEN-LAST:event_delete_invoice_ItemActionPerformed

    private void Create_New_ItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Create_New_ItemActionPerformed
         controller.showCreateLine(evt);
    }//GEN-LAST:event_Create_New_ItemActionPerformed

    private void Invoice_Line_TableMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Invoice_Line_TableMousePressed
        controller.clickLineTable(evt);   
    }//GEN-LAST:event_Invoice_Line_TableMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InvoiceFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InvoiceFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InvoiceFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InvoiceFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InvoiceFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Create_New_Item;
    private javax.swing.JButton Create_New_Ivvoice;
    private javax.swing.JLabel Customer_name;
    private javax.swing.JButton Delete_Invoice;
    private javax.swing.JLabel InvoiceTable;
    private javax.swing.JTable Invoice_Line_Table;
    private javax.swing.JMenu Menu;
    private javax.swing.JMenuBar MenuBar;
    private javax.swing.JLabel customer_name_label;
    private javax.swing.JButton delete_invoice_Item;
    private javax.swing.JLabel invoice_date;
    private javax.swing.JLabel invoice_date_label;
    private javax.swing.JLabel invoice_itemlabel;
    private javax.swing.JLabel invoice_number;
    private javax.swing.JLabel invoice_number_label;
    private javax.swing.JTable invoice_table_01;
    private javax.swing.JLabel invoice_total;
    private javax.swing.JLabel invoice_total_label;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JMenuItem load;
    private javax.swing.JMenuItem save;
    // End of variables declaration//GEN-END:variables

    public JTable getInvoiceHeaderTable() {
        return this.invoice_table_01;
    }

    public JTable getInvoiceLineTable() {
        return this.Invoice_Line_Table;
    }

    public JLabel getInvoiceNumberLabel() {
        return this.invoice_number_label;
    }

    public JLabel getInvoiceDateLabel() {
        return this.invoice_date_label;
    }

    public JLabel getInvoiceCustomerNameLabel() {
        return this.customer_name_label;
    }

    public JLabel getInvoiceTotalLabel() {
        return this.invoice_total_label;
    }

    public ArrayList<InvoiceHeader> getInvoices() {
        return invoices;
    }

}
